insert into CARD(id, card_title, card_text)
values ('056b808d-97c3-4a06-b588-1af008374145', 'pirmas',
        'Apie ankstyvus prekybinius ryšius tarp suomių ir baltų liudija baltiški skoliniai suomių kalboje. XIV a. Kareliją valdė Gedimino sūnus Narimantas (Karelijos kunigaikščiu buvo 1333–1348 m. laikotarpiu). Kitas epizodas apie Suomijos ir Lietuvos santykius – XVI a. Turku mieste gyvenęs hercogas Jonas Vaza veda Kotryną Jogailaitę. Ši santuoka ypač sustiprina švietimo mainus tarp tuometės LDK ir į Švedijos sudėtį įėjusios Suomijos – Suomijos ir Švedijos akademikai studijuodavo Vilniaus universitete, o paskui grįždavo atgal.Apie ankstyvus prekybinius ryšius tarp suomių ir baltų liudija baltiški skoliniai suomių kalboje. XIV a. Kareliją valdė Gedimino sūnus Narimantas (Karelijos kunigaikščiu buvo 1333–1348 m. laikotarpiu). Kitas epizodas apie Suomijos ir Lietuvos santykius – XVI a. Turku mieste gyvenęs hercogas Jonas Vaza veda Kotryną Jogailaitę. Ši santuoka ypač sustiprina švietimo mainus tarp tuometės LDK ir į Švedijos sudėtį įėjusios Suomijos – Suomijos ir Švedijos akademikai studijuodavo Vilniaus universitete, o paskui grįždavo atgal.'),
       ('b059043f-14b5-4ecc-ad97-679f74359cf1', 'antras',
        'Apie ankstyvus prekybinius ryšius tarp suomių ir baltų liudija baltiški skoliniai suomių kalboje. XIV a. Kareliją valdė Gedimino sūnus Narimantas (Karelijos kunigaikščiu buvo 1333–1348 m. laikotarpiu). Kitas epizodas apie Suomijos ir Lietuvos santykius – XVI a. Turku mieste gyvenęs hercogas Jonas Vaza veda Kotryną Jogailaitę. Ši santuoka ypač sustiprina švietimo mainus tarp tuometės LDK ir į Švedijos sudėtį įėjusios Suomijos – Suomijos ir Švedijos akademikai studijuodavo Vilniaus universitete, o paskui grįždavo atgal.Apie ankstyvus prekybinius ryšius tarp suomių ir baltų liudija baltiški skoliniai suomių kalboje. XIV a. Kareliją valdė Gedimino sūnus Narimantas (Karelijos kunigaikščiu buvo 1333–1348 m. laikotarpiu). Kitas epizodas apie Suomijos ir Lietuvos santykius – XVI a. Turku mieste gyvenęs hercogas Jonas Vaza veda Kotryną Jogailaitę. Ši santuoka ypač sustiprina švietimo mainus tarp tuometės LDK ir į Švedijos sudėtį įėjusios Suomijos – Suomijos ir Švedijos akademikai studijuodavo Vilniaus universitete, o paskui grįždavo atgal.o'),
       ('b9a0e092-b98f-4159-9a9e-7ffaf1270392', 'trecias',
        'Apie ankstyvus prekybinius ryšius tarp suomių ir baltų liudija baltiški skoliniai suomių kalboje. XIV a. Kareliją valdė Gedimino sūnus Narimantas (Karelijos kunigaikščiu buvo 1333–1348 m. laikotarpiu). Kitas epizodas apie Suomijos ir Lietuvos santykius – XVI a. Turku mieste gyvenęs hercogas Jonas Vaza veda Kotryną Jogailaitę. Ši santuoka ypač sustiprina švietimo mainus tarp tuometės LDK ir į Švedijos sudėtį įėjusios Suomijos – Suomijos ir Švedijos akademikai studijuodavo Vilniaus universitete, o paskui grįždavo atgal.Apie ankstyvus prekybinius ryšius tarp suomių ir baltų liudija baltiški skoliniai suomių kalboje. XIV a. Kareliją valdė Gedimino sūnus Narimantas (Karelijos kunigaikščiu buvo 1333–1348 m. laikotarpiu). Kitas epizodas apie Suomijos ir Lietuvos santykius – XVI a. Turku mieste gyvenęs hercogas Jonas Vaza veda Kotryną Jogailaitę. Ši santuoka ypač sustiprina švietimo mainus tarp tuometės LDK ir į Švedijos sudėtį įėjusios Suomijos – Suomijos ir Švedijos akademikai studijuodavo Vilniaus universitete, o paskui grįždavo atgal.o'),
       ('992576b8-a103-496f-9b0b-b0483c407570', 'ketvirtas',
        'Apie ankstyvus prekybinius ryšius tarp suomių ir baltų liudija baltiški skoliniai suomių kalboje. XIV a. Kareliją valdė Gedimino sūnus Narimantas (Karelijos kunigaikščiu buvo 1333–1348 m. laikotarpiu). Kitas epizodas apie Suomijos ir Lietuvos santykius – XVI a. Turku mieste gyvenęs hercogas Jonas Vaza veda Kotryną Jogailaitę. Ši santuoka ypač sustiprina švietimo mainus tarp tuometės LDK ir į Švedijos sudėtį įėjusios Suomijos – Suomijos ir Švedijos akademikai studijuodavo Vilniaus universitete, o paskui grįždavo atgal.Apie ankstyvus prekybinius ryšius tarp suomių ir baltų liudija baltiški skoliniai suomių kalboje. XIV a. Kareliją valdė Gedimino sūnus Narimantas (Karelijos kunigaikščiu buvo 1333–1348 m. laikotarpiu). Kitas epizodas apie Suomijos ir Lietuvos santykius – XVI a. Turku mieste gyvenęs hercogas Jonas Vaza veda Kotryną Jogailaitę. Ši santuoka ypač sustiprina švietimo mainus tarp tuometės LDK ir į Švedijos sudėtį įėjusios Suomijos – Suomijos ir Švedijos akademikai studijuodavo Vilniaus universitete, o paskui grįždavo atgal.');
INSERT INTO USERS(id, username, name, surname, country, city, street, zip_Code, phone_Number, password)
VALUES ('b606d6f2-f79c-4219-a33b-68d519b48048', 'user', 'user', 'useriauskas', 'Litvinas', 'Vilnius', 'Savanoriu',
        '854251', '860532164', '{bcrypt}$2a$10$jYIbAef1H7S.womsk7MRtOCSEx/DgM7CZ1nNeLLzoZ/OPs0a25DV2'),
       ('bd8968db-ad2a-4dd0-a0ab-7eebcc05427e', 'admin', 'adminas', 'adminiauskas', 'Litvinas', 'Kaunas', 'Kaunieciu',
        '854251', '860532164', '{bcrypt}$2a$10$VylYhXDaKC7W28tQTvYYkOdZIj2pnPVIobXOConbXy3xeBcF6Xuni');

INSERT INTO ROLES(id, name)
VALUES ('777e0319-0f1c-43cf-b1dc-62ce282d7765', 'USER'),
       ('95be10e4-62d7-4bb9-b70e-92f10cb3f6ab', 'ADMIN');
INSERT INTO USERS_ROLES(user_id, roles_id)
VALUES ('b606d6f2-f79c-4219-a33b-68d519b48048', '777e0319-0f1c-43cf-b1dc-62ce282d7765'),
       ('bd8968db-ad2a-4dd0-a0ab-7eebcc05427e', '777e0319-0f1c-43cf-b1dc-62ce282d7765'),
       ('bd8968db-ad2a-4dd0-a0ab-7eebcc05427e', '95be10e4-62d7-4bb9-b70e-92f10cb3f6ab');
